workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: "3.29.0"
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter upgrade
          flutter clean
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          flutter build ios --no-codesign
