# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  flutter_application_path = File.join(File.dirname(File.realpath(__FILE__)), '..', 'Flutter')
  load File.join(flutter_application_path, 'flutter_export_environment.sh')

  pod 'Flutter', :path => File.join(flutter_application_path, 'engine')
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
