# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Ensure the Flutter path is correct
  flutter_application_path = File.expand_path('..', __dir__)
  if File.exist?(File.join(flutter_application_path, 'Flutter', 'flutter_export_environment.sh'))
    load File.join(flutter_application_path, 'Flutter', 'flutter_export_environment.sh')
  end
  
  

  # Correctly reference Flutter
  pod 'Flutter', :path => '../Flutter'

  # Add Firebase correctly
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
