jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.1"  # Replace with your Flutter version
          architecture: x64  # Force x64 (Intel) instead of arm64

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --no-codesign
        
  build-ios:
    runs-on: macos-12  # Force Intel-based macOS runner